[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]
cmds = ["cd backend && npm ci --only=production"]

[phases.build]
cmds = ["echo 'Backend build complete'"]

[start]
cmd = "cd backend && npm start"

