[phases.setup]
nixPkgs = ['nodejs', 'postgresql', 'python3']

[phases.install]
cmds = ['cd backend && npm install']

[phases.build]
cmds = ['cd backend && npm run build']

[start]
cmd = 'cd backend && npm start'