[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["npm install --no-package-lock --legacy-peer-deps"]

[phases.build]
cmds = ["echo 'No build step required'"]

[start]
cmd = "npm start"
