[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["rm -f package-lock.json", "npm install --legacy-peer-deps"]

[phases.build]
cmds = ["echo 'No build step required'"]

[start]
cmd = "npm start"
